create table public.recipes (
  id uuid not null default gen_random_uuid (),
  dish_id uuid not null default gen_random_uuid (),
  dish_name text not null,
  servings numeric not null,
  ingredient_id uuid not null,
  ingredient_name text null,
  recipe_quantity numeric not null,
  recipe_unit text not null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  "IsFullRecipe" boolean null default true,
  "IsSubRecipe" boolean not null default false,
  ingredient_quantity numeric(10, 4) null,
  ingredient_unit text null,
  business_id uuid not null,
  recipe_group text null,
  full_recipe_id uuid null,
  volume_quantity double precision null,
  volume_unit text null,
  weight_quantity double precision null,
  weight_unit text null,
  "Ingredient_note" text null,
  "Recipe_note" text null,
  is_commissary boolean null,
  is_active boolean null,
  shelf_life_days integer null,
  cost_null_reason text null,
  sku_id bigint null,
  sku_pack_unit text null,
  cost_per_pack_unit numeric null,
  conversion_factor numeric null,
  sub_recipe_yield_unit text null,
  ingredient_total_cost numeric null,
  sub_recipe_cost_nulls jsonb null,
  min_batch_size integer null,
  max_batch_size integer null,
  recipe_group_min_distinct integer null,
  recipe_group_max_distinct integer null,
  cost_source text null,
  menu_price numeric null,
  cost_percent numeric null,
  final_price numeric null,
  prep_time_minutes integer null,
  storage_temp_fahrenheit integer null,
  serving_cost numeric null,
  constraint recipes_pkey primary key (id),
  constraint recipes_business_id_fkey foreign KEY (business_id) references businesses (id),
  constraint recipes_ingredient_id_fkey foreign KEY (ingredient_id) references ingredients (ingredient_id)
) TABLESPACE pg_default;